- name: Update cache
  apt: update_cache=yes

- name: Install software-properties-common
  apt: pkg=software-properties-common update_cache=yes

- apt_repository: repo='ppa:certbot/certbot'

- name: Updates cache
  apt: update_cache=yes

- name: Install python-certbot-nginx
  apt: pkg=python-certbot-nginx update_cache=yes

- name: Put renewal hook
  template: src=templates/01-reload-nginx.j2 dest=/etc/letsencrypt/renewal-hooks/deploy/01-reload-nginx
