- name: pre task
  become: yes
  apt:
    name:
      - python-simplejson
      - python-apt
    state: latest
    update_cache: yes

- name: Set timezone variables
  timezone:
    name: Asia/Tokyo

# - hosts: all
#   tasks:
#   - name: apt-get clean
#     shell: apt-get clean
#     become: true
#   - name: apt-get update
#     shell: apt-get update
#     become: true
#   - apt: name=aptitude state=present
#   - apt: update_cache=yes upgrade=safe cache_valid_time=3600
  
- name: 基本的なパッケージをインストール
  become: yes
  apt:
    name:
      - build-essential
      - libsqlite3-dev
      - libxml2
      - sqlite3
      - zip
      - emacs25-nox
      - git
      - zsh
      - lv
      - autoconf
      - bison
      - libffi-dev
      - ruby
      - aptitude
      - memcached
    state: latest
    update_cache: yes
  tags: packages

- name: Updates cache
  become: yes
  apt: update_cache=yes
- name: Upgrade full
  become: yes
  apt: upgrade=full

